language: elixir
sudo: false
cache:
  directories:
    - deps

script:
  - mix test
  - if [[ `elixir -v` = *"1.8"* ]]; then mix format --check-formatted; fi

matrix:
  include:
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.7
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 22.0.1
    - elixir: 1.12.3
      otp_release: 24.0.2
